# Generated by Django 3.1.3 on 2020-12-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.AutoField(help_text='id', primary_key=True, serialize=False)),
                ('account_name', models.CharField(help_text='账目名称', max_length=64)),
                ('type', models.CharField(default=1, help_text='账目类型', max_length=64)),
                ('income_type', models.CharField(default=1, help_text='收入类型', max_length=64)),
                ('consume_type', models.CharField(default=1, help_text='消费类型', max_length=64)),
                ('lend_type', models.CharField(default=1, help_text='借出类型', max_length=64)),
                ('manage_money_type', models.CharField(default=1, help_text='理财类型', max_length=64)),
                ('comments', models.CharField(help_text='备注', max_length=64, null=True)),
                ('income_time', models.CharField(help_text='收入时间', max_length=32, null=True)),
                ('consume_time', models.CharField(help_text='消费时间', max_length=32, null=True)),
                ('lend_time', models.CharField(help_text='借出时间', max_length=32, null=True)),
                ('manage_money_time', models.CharField(help_text='理财时间', max_length=32, null=True)),
            ],
            options={
                'db_table': 'manage',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='guest', help_text='用户名', max_length=64, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=64)),
                ('role', models.CharField(default=2, help_text='用户等级', max_length=32)),
                ('register_time', models.DateTimeField(auto_now=True, help_text='注册时间')),
                ('login_time', models.CharField(default='Null', help_text='登录时间', max_length=64)),
                ('icon', models.CharField(default='/icon/default.png', help_text='用户头像地址', max_length=64)),
                ('session', models.CharField(help_text='session', max_length=64)),
                ('comments', models.CharField(default='游客', help_text='备注', max_length=64)),
                ('login_name', models.CharField(default='Null', help_text='登录用户名', max_length=64)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
